"""Add os_version to Device

Revision ID: 3b33788ae578
Revises: 1455e8ce5308
Create Date: 2025-08-16 11:34:35.574902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b33788ae578'
down_revision = '1455e8ce5308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('os_version', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_column('os_version')

    # ### end Alembic commands ###
