"""Add last_seen column to Device model

Revision ID: 3eab59403e9a
Revises: 
Create Date: 2025-08-05 14:23:49.600000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eab59403e9a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    with op.batch_alter_table('device_location_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_location_history_serial_number'), ['serial_number'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_location_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_location_history_serial_number'))

    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_column('last_seen')

    # ### end Alembic commands ###
